runtime: nodejs20
service: fe-0777
instance_class: F1

handlers:
  - url: /
    static_files: public/index.html
    upload: public/index.html

  - url: /(.*)
    static_files: public/\1
    upload: public/(.*)

default_expiration: "1h"